import {useEffect, useState} from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import tw from "tailwind-styled-components";
import Map from '../components/Map';


export default function Home() {
  return (
      <Wrapper>
          <Head>
          <title>Uber Clone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/vercel.svg" />
        </Head>
        <Map/>
        <ActionItems>
          <Header>
            <UberLogo src='https://i.ibb.co/84stgjq/uber-technologies-new-20218114.jpg'/>
            <Profile>
              <Name> Mohd Rashid</Name>
              <UserImage src='/pf2.png' />
            </Profile>
           </Header>
           <ActionButtons>
             <Link href='/Search' >
              <ActionButton> 
                 <ActionButtomImage src='https://i.ibb.co/1nStPWT/uberblacksuv.png' /> 
                  Ride
              </ActionButton>
             </Link>
             <ActionButton>
               <ActionButtomImage src='https://i.ibb.co/n776JLm/bike.png' /> Wheels
             </ActionButton>
             <ActionButton> 
               <ActionButtomImage src='https://i.ibb.co/5RjchBg/uberschedule.png' />
               Reserve</ActionButton>
           </ActionButtons>
           <InputButton>
            Where to?
           </InputButton>
        </ActionItems>
      </Wrapper>
  )
}
const Wrapper = tw.div`
  flex
  h-screen
  flex-col
`
const ActionItems = tw.div`
  flex-1 p-5
`;
const Header = tw.div`
flex items-center justify-between
`;
const Profile = tw.div`
  flex items-center
`;
const UberLogo=tw.img`
  h-28
`;
const Name=tw.div`
  mr-5
`;
const UserImage=tw.img`
  h-14 w-14 rounded-full border border-gray-200 p-1
`;
const ActionButtons = tw.div`
flex flex-row `;
const ActionButton = tw.div`
  flex m-2 h-32  bg-gray-200 flex-1 items-center flex-col rounded-lg justify-center transform hover:scale-105 transition cursor-pointer text-xl 
`;
const ActionButtomImage = tw.img`
  h-3/5
`
const InputButton = tw.div`
bg-gray-200 flex items-center mt-8 p-4 cursor-pointer text-2xl rounded-lg`;
